### ISSUE TITLE
Access Issue

### ISSUE THREAD

**Issue by codewaves19** [codewaves19/Project-A#1]

**Comment by resumecode2** [comment]
1nijDC3gjIWkxWDD7hytHNUIAvQeIfh7G02b2v7taRgU should work without login

**Comment by resumecode2** [comment]
1nijDC3gjIWkxWDD7hytHNUIAvQeIfh7G02b2v7taRgU

**Comment by codewaves19** [comment]
Any updates on this?

**Comment by resumecode2** [comment]
This doesn't fix it.

**Comment by resumecode2** [comment]
Perhaps try again?
